# Generated by Django 2.2 on 2020-01-13 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='メールアドレス')),
                ('diary', models.CharField(max_length=500, verbose_name='日記')),
                ('positive', models.FloatField(default=0, verbose_name='ポジティブ')),
                ('negative', models.FloatField(default=0, verbose_name='ネガティブ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=8, unique=True, verbose_name='パスワード')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ログイン日時')),
            ],
        ),
        migrations.CreateModel(
            name='WordDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='ワード')),
                ('negaposi', models.FloatField(default=0, verbose_name='ネガポジ')),
            ],
        ),
    ]
