# Generated by Django 2.2 on 2020-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='negative',
            field=models.FloatField(verbose_name='ネガティブ'),
        ),
        migrations.AlterField(
            model_name='worddict',
            name='word',
            field=models.CharField(max_length=255, unique=True, verbose_name='ワード'),
        ),
    ]
