# Generated by Django 2.2 on 2020-01-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200113_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddict',
            name='word',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='ワード'),
        ),
    ]
