# Generated by Django 2.2 on 2020-01-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200113_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddict',
            name='word',
            field=models.CharField(default=None, max_length=255, verbose_name='ワード'),
        ),
    ]
